@startuml
!theme vibrant
title: 6.7. Создание новых данных
skinparam maxMessageSize 300
autonumber

participant "Пользователь" as user
box "Компьютер пользователя" #DEDEDE
    participant "CLI Клиент" as client
    database "Файловая система" as file
end box

box "GophKeeper" #d3f3fa
    participant "Обработчик запроса" as handler
    participant "Юзкейз добавления данных" as usecase
    participant "Служба шифрования" as crypto
    database "postgres" as db
end box

user -> client ++ : Вводит команду на создание новых данных
note over user, client
    GophKeeper create credentials site.com mylogin mypassword
end note

ref over user, handler
    6.5. Авторизация пользователя на стороне клиента
end

client -> client: Валидация введенных данных

opt Данные невалидны
    client -> user: Сообщение об ошибке
end

client -> handler ++ : Отправляет запрос на создание новых данных
note over client, handler
    POST /api/credentials/new HTTP/1.1
    Content-Type: application/json
    Authorization: Bearer ...
    
    {
        "name": "site.com",
        "login": "mylogin",
        "password": "mypassword",
    }
end note

group middleware
    note over user, handler: 6.4. Авторизация пользователя на стороне сервера
end group

handler -> handler: Парсит JSON и валидирует формат входных данных из тела запроса
opt Формат некорректен
    handler -> client: HTTP 400 Bad Request
    note over client, handler
        400 Bad Request HTTP/1.1
        Content-Type: application/json
    end note
    client --> user: Выводит сообщение об ошибке
end

handler -> usecase ++ : Вызывает поведение по созданию новых данных
usecase -> db ++ : Поиск существующих данных
return Пользовательские данные
opt Данные с таким именем уже существуют
    usecase --> handler: Данные с таким именем уже существуют
    handler --> client: HTTP 409 Conflict
    note over client, handler
        409 Conflict HTTP/1.1
        Content-Type: application/json
    end note
    client --> user: Выводит сообщение об ошибке
end

usecase -> crypto ++ : Шифрует данные
return Зашифрованные данные

usecase -> db : Сохраняет данные
activate db
deactivate db

return Успешно сохранено
return HTTP 201 Created
note over client, handler
    201 Created HTTP/1.1
    Content-Type: application/json
end note

client -> file: Сохраняет данные в файл и шифрует его
activate file
deactivate file 
return Вывод сообщения об успехе исполнения команды
@enduml