@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

skinparam wrapWidth 400
LAYOUT_WITH_LEGEND()

title
    <b>[System Context] Менеджер паролей «GophKeeper»</b>
end title

Person(user, "Пользователь", "Пользователь менеджера паролей «GophKeeper»")

Boundary(devices, "Устройства пользователя") {

    Boundary(pc, "Компьютер пользователя") {
        System(client, "Клиент менеджера паролей «GophKeeper»", "Клиентская часть системы безопасного хранения паролей")
    }

    Boundary(pc2, "Компьютер пользователя") {
        System(client2, "Клиент менеджера паролей «GophKeeper»", "Клиентская часть системы безопасного хранения паролей")
    }

    Boundary(pcN, "Компьютер пользователя") {
        System(clientN, "Клиент менеджера паролей «GophKeeper»", "Клиентская часть системы безопасного хранения паролей")
    }
}

System(server, "Менеджер паролей «GophKeeper»", "Серверная часть системы безопасного хранения паролей")

Rel(user, client, "Использует клиент для взаимодействия с системой хранения паролей «GophKeeper»")
Rel(user, client2, "Использует клиент для взаимодействия с системой хранения паролей «GophKeeper»")
Rel(user, clientN, "Использует клиент для взаимодействия с системой хранения паролей «GophKeeper»")
Rel(client, server, "Отправляет запросы на регистрацию, авторизацию, аутентификацию и взаимодействие с данными", "HTTP")
Rel(client2, server, "Отправляет запросы на регистрацию, авторизацию, аутентификацию и взаимодействие с данными", "HTTP")
Rel(clientN, server, "Отправляет запросы на регистрацию, авторизацию, аутентификацию и взаимодействие с данными", "HTTP")
@enduml