basePath: /api/v1
host: 0.0.0.0:8080
info:
  contact: {}
  description: Сервис хранения логинов, паролей, бинарных данных и прочей приватной
    информации.
  title: GophKeeper API
paths:
  /health:
    get:
      operationId: health
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Запрос состояния сервиса
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
